version: 0.2

phases:
  install:
    commands:
    # printenv
    # pwd
    - mkdir -p /go/src/github.com/weAutomateEverything/bankhal
    - cp -R * /go/src/github.com/weAutomateEverything/bankhal/
  pre_build:
    commands:

    finally:

  build:
    commands:
    - go get github.com/weAutomateEverything/bankhal
    - CGO_ENABLED=0   GOOS=linux go build -ldflags '-linkmode=external' -o ./bankhal github.com/weAutomateEverything/bankhal
    - go get -u github.com/go-swagger/go-swagger/cmd/swagger
    - swagger generate spec -m -o ./swagger.json
  post_build:
    commands:

    finally:

artifacts:
  files:
  - bankhal
  - swagger.json
  - Dockerfile
  - cacert.pem
cache:
  paths:
