apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hal
  name: hal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hal
  template:
    metadata:
      labels:
        app: hal
    spec:
      containers:
      - image: zamedic/bankhal:1.719.1
        name: hal
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: hal
        - secretRef:
            name: hal
        env:
        - name: MONGO_DATABASE
          value:
